[project]
name = "tip-llm-genai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "dotenv>=0.9.9",
    "google-genai>=1.20.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
